"""Export hydration-site results to tabular and molecular-visualisation formats."""

from __future__ import annotations

import csv
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from hydrarank.exceptions import HydraRankError


def write_csv(rows: Sequence[dict[str, Any]], path: str | Path) -> Path:
    """Write result rows to CSV using their existing field order."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        raise HydraRankError("cannot write CSV: there are no hydration sites")
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    return path


def write_site_coordinates(rows: Sequence[dict[str, Any]], path: str | Path) -> Path:
    """Write site centres as PDB or mmCIF, inferred from the file extension."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        raise HydraRankError("cannot write site coordinates: there are no hydration sites")
    suffix = path.suffix.lower()
    if suffix == ".pdb":
        _write_pdb(rows, path)
    elif suffix in {".cif", ".mmcif"}:
        _write_mmcif(rows, path)
    else:
        raise HydraRankError("site-coordinate output must end in .pdb, .cif or .mmcif")
    return path


def _write_pdb(rows: Sequence[dict[str, Any]], path: Path) -> None:
    lines = [
        "REMARK Hydration-site centres generated by HydraRank",
        "REMARK Occupancy is stored in occupancy; -TdS is stored in the B-factor.",
    ]
    for serial, row in enumerate(rows, 1):
        site = int(row["site"])
        occupancy = float(row.get("occupancy", 0.0))
        score = float(row.get("minus_t_delta_s", 0.0))
        lines.append(
            f"HETATM{serial:5d}  O   HOH W{site:4d}    "
            f"{float(row['x']):8.3f}{float(row['y']):8.3f}{float(row['z']):8.3f}"
            f"{occupancy:6.2f}{score:6.2f}          O"
        )
    lines.extend(["TER", "END"])
    path.write_text("\n".join(lines) + "\n")


def _write_mmcif(rows: Sequence[dict[str, Any]], path: Path) -> None:
    lines = [
        "data_hydrarank_sites",
        "#",
        "loop_",
        "_atom_site.group_PDB",
        "_atom_site.id",
        "_atom_site.type_symbol",
        "_atom_site.label_atom_id",
        "_atom_site.label_comp_id",
        "_atom_site.label_asym_id",
        "_atom_site.label_seq_id",
        "_atom_site.Cartn_x",
        "_atom_site.Cartn_y",
        "_atom_site.Cartn_z",
        "_atom_site.occupancy",
        "_atom_site.B_iso_or_equiv",
    ]
    for serial, row in enumerate(rows, 1):
        lines.append(
            f"HETATM {serial} O O HOH W {int(row['site'])} "
            f"{float(row['x']):.3f} {float(row['y']):.3f} {float(row['z']):.3f} "
            f"{float(row.get('occupancy', 0.0)):.3f} "
            f"{float(row.get('minus_t_delta_s', 0.0)):.3f}"
        )
    lines.append("#")
    path.write_text("\n".join(lines) + "\n")
